### ISSUE TITLE
[💡 New] Reintroduce pull requests

### ISSUE THREAD

**Issue by RubenTheCoder** [RubenTheCoder/Shunji-Railways-GitHub#71]
### What kind of idea is it?

Add pull requests back

### Describe in more details what it looks like

We can re-include pull requests, but without locking the main branch, because that's so annoying when accidently working in the main branch. Instead lock the already released versions and github stables.

To implement, we also need to update the guides on the wiki and the contributing guidelines and such.

We can add this from the first new github stable

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

---

### Tasks

- [x] Create a pull request template
- [x] Create a wiki guide on how to use branches and pull requests
