### ISSUE TITLE
[🏗 Phase] Design UI and UX mockups

### ISSUE THREAD

**Issue by RubenTheCoder** [RubenTheCoder/Shunji-Railways-GitHub#73]
### What phase is this for

Phase 1

### What needs to be done to complete this phase

Create design mockups for the website and put these on a new wiki page.

## Todo
- [ ] Create design mockups for:
  - [x] The homepage.
  - [x] The header.
  - [x] The footer.
  - [ ] The route planner widget.
  - [x] The navigation menu.
  - [ ] The contact page.
  - [ ] The auto generated article pages.
  - [ ] Other things that might pop up.
- [ ] Create mockups for the UX (user experience), for things and requirements of things like buttons, contrast, responsiveness, and sort-alike.
- [x] Create a wiki page to host these mockups, stored inside the .github images folder
- [x] Link the wiki page and put it inside the art section
 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
