### ISSUE TITLE
[🪛 Update] Move GitHub images to subfolders

### ISSUE THREAD

**Issue by RubenTheCoder** [RubenTheCoder/Shunji-Railways-GitHub#74]
### What kind of update is it?

Organization of the GitHub images folder

### Describe in more details what it looks like

The amount of images is cluttering the images folder. Try to create subfolders, move the images into there using VS code, and bypassing the .gitignore for a moment and update the image paths.

## Todo

- [x] Open the images folder in VS code.
- [x] Move the images into subfolders.
- [x] Rename some images now you easily can.
- [x] Disable the .gitignore file to upload it
- [x] Update all links to point to the correct paths

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
